root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/server"
  bin = "./tmp/server"
  full_bin = "PORT=8080 ./tmp/server"
  include_ext = ["go", "sql"]
  exclude_dir = ["tmp"]
  delay = 500
  stop_on_error = true

[log]
  time = true

[misc]
  clean_on_exit = true
